baseURL = "/"
languageCode = "en-us"
title = "POTRex"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "PornHub Tracking Exposed"
    subsite = "pornhub"
    description = "is the pornhub algorithm kidding with your perception of sex?"
    tagline = "Watch a tech-company f*ck your behavior data!"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    name = "About&Contacts"
    url = "/about/"
    weight = 20
 [[menu.main]]
    name = "Slides"
    url = "/slides/"
    weight = 40
 [[menu.main]]
    name = "tracking.exposed"
    url = "https://tracking.exposed"
    weight = 70
 [[menu.main]]
    name = "Other Tools"
    url = "/about/"
    weight = 50


 [[menu.featured]]
    name = "Algorithm Domination"
    url = "/preview"
    weight = -100
    pre = "/images/algorithmdom.svg"
    post = "Some of your data and what your master wants you to masturbate to today"
 [[menu.featured]]
    name = "Collective test"
    url = "/potest/"
    weight = -90
    pre = "/images/compare.svg"
    post = "joining the gang test. Once in a while, we perform the same actions to infer personalization"
 [[menu.featured]]
    name = "Behind the Scenes"
    url = "/pov"
    weight = -80
    pre = "/images/pov.svg"
    post = "See through our POV and play hard with our pleasure tools"

[[menu.footer]]
   page = "Tracking Exposed"
   identifier = "trex"
   name = "Umbrella project: Tracking Exposed"
   url = "https://tracking.exposed"
   weight = 90
